
import { FormData } from '../types';

/**
 * NOTE: This is a SIMULATION of the `docx` library functionality.
 * In a real-world application, you would install the `docx` package
 * and use its API to create a proper DOCX file in memory.
 * For this example, we generate a formatted text string and trigger
 * a download with a .docx extension.
 */

export const generateDocx = (formData: FormData, templateText: string): void => {
  // Replace placeholders in the template with form data
  let filledTemplate = templateText
    .replace(/\[PARTY_A_NAME\]/g, formData.partyAName || '__________________')
    .replace(/\[PARTY_A_ADDRESS\]/g, formData.partyAAddress || '__________________')
    .replace(/\[PARTY_B_NAME\]/g, formData.partyBName || '__________________')
    .replace(/\[PARTY_B_ADDRESS\]/g, formData.partyBAddress || '__________________')
    .replace(/\[EFFECTIVE_DATE\]/g, formData.effectiveDate ? new Date(formData.effectiveDate).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }) : '__________________')
    .replace(/\[SCOPE_OF_WORK\]/g, formData.scopeOfWork || '__________________')
    .replace(/\[COMPENSATION_AMOUNT\]/g, formData.compensationAmount ? `$${parseFloat(formData.compensationAmount).toLocaleString()}` : '__________________');

  // Simulate DOCX generation by creating a Blob.
  // In a real app, this blob would be generated by `docx.Packer.toBlob(doc)`.
  const blob = new Blob([filledTemplate], { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' });

  // Create a download link and trigger the download
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  
  // Sanitize file name
  const fileName = `${formData.agreementType.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.docx`;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  
  // Clean up
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
